name: 'Auto-deletes Branches'
description: 'Automatically deletes old branches within the '
inputs:
  region:
    required: true
    description: 'Default Region for AWS'
  access:
    required: true
    description: 'Access Key for AWS Account User'
  secret:
    required: true
    description: 'Secret Key for AWS Account User'
  stackname:
    required: true
    description: 'Name of the Cloudformation Stack'
runs:
  using: 'docker'
  image: 'Dockerfile'
